### ISSUE TITLE
Abbreviated syntax for redirects

### ISSUE THREAD

**Issue by evan10s** [HackGT/beehive#21]
Currently the way you define a URL to redirect is this slightly convoluted/unintuitive bit of YAML:
```yaml
git: https://github.com/HackGT/redirector.git
env:
  REDIRECT_URL: "https://registration.build.hack.gt"
```
It'd be nice if you could just write `redirect: https://registration.build.hack.gt` and biodomes would do the above internally, without me having to write all of it out.
